
export interface PRData {
  id: string;
  title: string;
  description: string;
  author: string;
  baseRef: string;
  headRef: string;
  files: FileChange[];
  warning?: string;
}

export type FileStatus = 'added' | 'modified' | 'deleted' | 'renamed' | 'unchanged';

export interface FileChange {
  path: string;
  status: FileStatus;
  additions: number;
  deletions: number;
  oldContent?: string;
  newContent: string;
}

export interface Walkthrough {
  title: string;
  author?: string;
  sections: WalkthroughSection[];
}

export interface WalkthroughSection {
  id: string;
  title: string;
  files: string[];
  description: string;
  highlights?: CodeHighlight[];
}

export interface CodeHighlight {
  file: string;
  lines: [number, number];
  note: string;
}

export interface ViewportState {
  file: string | null;
  startLine: number;
  endLine: number;
}

export interface SelectionState {
  file: string;
  startLine: number;
  endLine: number;
  content: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'system' | 'assistant';
  content: string;
  timestamp: number;
  context?: {
    file: string;
    lineRange?: [number, number];
  };
}

export interface FileTreeNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: FileTreeNode[];
  data?: FileChange;
}

export interface PRHistoryItem {
  id: string;
  url: string;
  title: string;
  timestamp: number;
  author: string;
}

export type AnnotationType = 'marker' | 'label';

export interface Annotation {
  id: string;
  file: string;
  line: number;
  type: AnnotationType;
  title?: string;
  description?: string;
  timestamp: number;
}

export interface LinearIssue {
  identifier: string;
  title: string;
  description: string;
  url: string;
  state?: string;
}

export interface CodeReference {
  id: string;
  description: string;
  filepath: string;
  line: number;
  resolvedPath: string | null;
  status: 'valid' | 'unresolved' | 'file-not-in-pr';
}

export interface NavigationTarget {
  filepath: string;
  line: number;
  source: 'diagram' | 'walkthrough' | 'annotation' | 'search' | 'tree';
  diagramId?: string;
  referenceId?: string;
}

export interface Diagram {
  id: string;
  title: string;
  description: string;
  mermaidCode: string;
  references?: CodeReference[];
  timestamp: number;
  isAutoGenerated?: boolean;
}
