
import { GoogleGenAI } from "@google/genai";
import { PRData, Diagram, CodeReference } from '../types';
import { resolveFilePath } from '../utils/fileUtils';

export class DiagramAgent {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  }

  private parseMermaidReferences(rawCode: string = "", prFiles: string[]): { cleanedCode: string, references: CodeReference[] } {
    const references: CodeReference[] = [];
    if (!rawCode) return { cleanedCode: "", references: [] };
    
    // Pattern: {description}§{filepath}:{line}
    const refPattern = /([^:\n>]+)§([^:\n]+):(\d+)/g;
    
    const cleanedCode = rawCode.replace(refPattern, (match, description, filepath, lineStr) => {
      const line = parseInt(lineStr, 10);
      const refId = `ref-${Math.random().toString(36).substr(2, 9)}`;
      
      const resolution = resolveFilePath(filepath.trim(), prFiles);
      
      references.push({
        id: refId,
        description: description.trim(),
        filepath: filepath.trim(),
        line: isNaN(line) ? 1 : line,
        resolvedPath: resolution.resolved,
        status: resolution.resolved ? 'valid' : 'unresolved'
      });
      
      return description.trim();
    });

    return { cleanedCode, references };
  }

  async proposeDiagrams(prData: PRData): Promise<Diagram[]> {
    const prFilePaths = prData.files.map(f => f.path);
    const fileContext = prData.files
      .filter(f => f.status !== 'deleted' && (f.path.endsWith('.ts') || f.path.endsWith('.tsx') || f.path.endsWith('.py') || f.path.endsWith('.js')))
      .map(f => `File: ${f.path}\nContent:\n${(f.newContent || '').slice(0, 3000)}`)
      .join('\n\n');

    const prompt = `
      You are Theia, specialized Software Architecture Agent.
      Analyze these Pull Request changes and generate Mermaid.js Sequence Diagrams.

      PR Title: ${prData.title}
      PR Description: ${prData.description}

      CODE CONTEXT:
      ${fileContext}

      ## Code Reference Format (CRITICAL)
      Every message, activation, or note in the diagram MUST use this format:
      {description}§{filepath}:{line}

      Where:
      - § is the literal section sign character (Unicode U+00A7)
      - Return ONLY a JSON array. 
    `;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
        config: {
          responseMimeType: "application/json"
        }
      });

      const text = response.text;
      if (!text) throw new Error("No response from AI");

      const rawDiagrams = JSON.parse(text);
      if (!Array.isArray(rawDiagrams)) throw new Error("AI returned malformed diagram list");
      
      return rawDiagrams.map((d: any, idx: number) => {
        const { cleanedCode, references } = this.parseMermaidReferences(d.mermaidCode || "", prFilePaths);
        return {
            id: `auto-diagram-${Date.now()}-${idx}`,
            title: d.title || "Untitled Diagram",
            description: d.description || "No description provided",
            mermaidCode: cleanedCode,
            references,
            timestamp: Date.now(),
            isAutoGenerated: true
        };
      });
    } catch (e) {
      console.error("Diagram Generation Failed", e);
      throw e;
    }
  }

  async generateCustomDiagram(prData: PRData, userPrompt: string): Promise<Diagram> {
    const prFilePaths = prData.files.map(f => f.path);
    const prompt = `Generate a Mermaid.js Sequence Diagram for: "${userPrompt}". 
    Use format: {description}§{filepath}:{line}. Return JSON.`;

    try {
      const response = await this.ai.models.generateContent({
          model: 'gemini-3-flash-preview',
          contents: prompt,
          config: { responseMimeType: "application/json" }
      });
      
      const text = response.text;
      if (!text) throw new Error("No response from AI");
      
      const data = JSON.parse(text);
      const { cleanedCode, references } = this.parseMermaidReferences(data.mermaidCode || "", prFilePaths);
      
      return {
          id: `custom-diagram-${Date.now()}`,
          title: data.title || "Custom Diagram",
          description: data.description || "User-defined flow",
          mermaidCode: cleanedCode,
          references,
          timestamp: Date.now(),
          isAutoGenerated: false
      };
    } catch (e) {
      console.error("Custom Diagram Generation Failed", e);
      throw e;
    }
  }
}
