
/** Review-intent mode: what the AI focuses on for this session (see src/prompts/modeInstructions.ts). */
export type AppMode = 'pr' | 'learn' | 'dive' | 'custom';

export interface PRData {
  id: string;
  title: string;
  description: string;
  author: string;
  baseRef: string;
  headRef: string;
  files: FileChange[];
  warning?: string;
  // Phase 9: Full Repo Context
  owner?: string;          // Repository owner (for API calls)
  repo?: string;           // Repository name (for API calls)
  headSha?: string;        // HEAD commit SHA (for fetching files)
  repoTree?: RepoNode[];   // Full repository tree (lazy loaded)
  // Explicit capability flag — whether this PRData can be fetched/refreshed
  // remotely. Undefined (persisted state from before this field existed)
  // falls back to owner/repo/headSha presence; see canFetchRemote() in
  // src/modules/ingestion/PRSourceService.ts.
  canFetchRemote?: boolean;
}

/**
 * Phase 9: Repository tree node - lightweight reference to any file in the repo.
 * Used for the "Lazy Graph" architecture to enable navigation beyond PR files.
 */
export interface RepoNode {
  path: string;            // Full path: "src/utils/auth.ts"
  type: 'blob' | 'tree';   // 'blob' = file, 'tree' = directory
  sha: string;             // Git SHA for fetching content
  mode?: string;           // File mode (e.g., "100644")
  size?: number;           // File size in bytes (only for blobs)
}

/**
 * Phase 9: A lazily-loaded file (not part of PR changes).
 * Used for displaying non-PR files in read-only mode.
 */
export interface LazyFile {
  path: string;
  content: string;
  sha: string;
  isReadOnly: true;        // Always true for non-PR files
  fetchedAt: number;       // Timestamp for cache management
}

export type FileStatus = 'added' | 'modified' | 'deleted' | 'renamed' | 'unchanged';

export interface FileChange {
  path: string;
  status: FileStatus;
  additions: number;
  deletions: number;
  oldContent?: string;
  newContent: string;
  /** Set when a per-file content fetch failed — newContent/oldContent are '' as a placeholder, not genuine empty files. */
  contentUnavailable?: boolean;
}

export interface Walkthrough {
  title: string;
  author?: string;
  sections: WalkthroughSection[];
}

export interface WalkthroughSection {
  id: string;
  title: string;
  files: string[];
  description: string;
  highlights?: CodeHighlight[];
}

export interface CodeHighlight {
  file: string;
  lines: [number, number];
  note: string;
}

export interface ViewportState {
  file: string | null;
  startLine: number;
  endLine: number;
}

export interface SelectionState {
  file: string;
  startLine: number;
  endLine: number;
  content: string;
  /** Which diff side each end of the selection anchored to — absent means 'new' (pre-existing single-side selections). */
  startSide?: 'old' | 'new';
  endSide?: 'old' | 'new';
  /** 'side:line' keys of every rendered row the selection spans, for exact membership checks across mixed old/new selections. */
  selectedCoords?: Set<string>;
}

export interface GroundingChunk {
  web?: {
    uri: string;
    title: string;
  };
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'system' | 'assistant';
  content: string;
  timestamp: number;
  context?: {
    file: string;
    lineRange?: [number, number];
  };
  groundingChunks?: GroundingChunk[];
}

export interface FileTreeNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: FileTreeNode[];
  data?: FileChange;
}

export interface PRHistoryItem {
  id: string;
  url: string;
  title: string;
  timestamp: number;
  author: string;
}

export type AnnotationType = 'marker' | 'label';

export interface Annotation {
  id: string;
  file: string;
  line: number;
  /** Which side of a diff `line` addresses. Absent on annotations persisted before this field existed — treat as 'new'. */
  side?: 'old' | 'new';
  type: AnnotationType;
  title?: string;
  description?: string;
  timestamp: number;
}

export interface LinearIssue {
  identifier: string;
  title: string;
  description: string;
  url: string;
  state?: string;
}

export interface CodeReference {
  id: string;
  description: string;
  filepath: string;
  line: number;
  resolvedPath: string | null;
  status: 'valid' | 'unresolved' | 'file-not-in-pr';
}

export interface NavigationTarget {
  filepath: string;
  line: number;
  source: 'diagram' | 'walkthrough' | 'annotation' | 'search' | 'tree';
  diagramId?: string;
  referenceId?: string;
  /** Which diff side to address `line` on. Defaults to 'new' when absent. */
  side?: 'old' | 'new';
}

export type DiagramCategory = 'interaction' | 'structure';
export type DiagramType = 'sequence' | 'flowchart' | 'class' | 'state';

export interface Diagram {
  id: string;
  title: string;
  description: string;
  mermaidCode: string;
  references?: CodeReference[];
  timestamp: number;
  isAutoGenerated?: boolean;
  category?: DiagramCategory;
  type?: DiagramType;
}

/** F5: A free-form review note on the whiteboard (not tied to a specific file/line). */
export interface Note {
  id: string;
  text: string;
  timestamp: number;
}
